version: "3.8"

services:
    mongodb:
        image: mongo:4.0.3
        ports:
            - "27017:27017"
        volumes:
            - dbdata6:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: root
volumes:
    dbdata6:
